apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: palworld-4
spec:
  title: '幻兽帕鲁私服4人房'
  url: 'https://github.com/thijsvanloef/palworld-server-docker'
  gitRepo: 'https://github.com/thijsvanloef/palworld-server-docker'
  author: 'Sealos'
  description: '该私服最多可容纳 4 个玩家流畅玩耍'
  readme: 'https://raw.githubusercontent.com/thijsvanloef/palworld-server-docker/main/README.md'
  icon: 'https://raw.githubusercontent.com/labring-actions/templates/main/template/palworld/logo.jpg'
  templateType: inline
  defaults:
    app_name:
      type: string
      value: palworld-4-${{ random(8) }}
  inputs:
    ADMIN_PASSWORD:
      description: "Secure administration access in the server with a password"
      type: string
      default: ""
      required: true
    SERVER_NAME:
      description: "A name for your community server"
      type: string
      default: ""
      required: false
    SERVER_PASSWORD:
      description: "Secure your community server with a password"
      type: string
      default: ""
      required: false

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: registry.cn-hangzhou.aliyuncs.com/bxy4543/palworld-server-docker:dev1
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: take-data-dir-ownership
          image: alpine
          # Give `grafana` user (id 472) permissions a mounted volume
          # https://github.com/grafana/grafana-docker/blob/master/Dockerfile
          command: ["/bin/sh", "-c", "chown -R 1000:1000 /palworld; chmod -R 770 /palworld; if [ -d /palworld/Pal/Saved/Config/LinuxServer ]; then cp /tmp/PalWorldSettings.ini /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; fi"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-tmpvn-palworldsettingsvn-ini
              mountPath: /tmp/PalWorldSettings.ini
              subPath: ./tmp/PalWorldSettings.ini
            - name: vn-palworld
              mountPath: /palworld
      containers:
        - name: ${{ defaults.app_name }}
          image: registry.cn-hangzhou.aliyuncs.com/bxy4543/palworld-server-docker:dev1
          env:
            - name: ServerIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: PORT
              value: "8211"
            - name: PLAYERS
              value: "4"
            - name: MULTITHREADING
              value: "true"
            - name: RCON_ENABLED
              value: "true"
            - name: RCON_PORT
              value: "25575"
            - name: ADMIN_PASSWORD
              value: ${{ inputs.ADMIN_PASSWORD }}
            - name: COMMUNITY
              value: "true"
            - name: SERVER_PASSWORD
              value: ${{ inputs.SERVER_PASSWORD }}
            - name: SERVER_NAME
              value: ${{ inputs.SERVER_NAME }}
          resources:
            requests:
              cpu: 1000m
              memory: 8192Mi
              ephemeral-storage: 400Mi
            limits:
              cpu: 4000m
              memory: 16384Mi
              ephemeral-storage: 400Mi
          ports:
            - containerPort: 8211
              name: game
              protocol: UDP
            - containerPort: 27015
              name: query
              protocol: UDP
            - containerPort: 25575
              name: rcon
              protocol: UDP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-tmpvn-palworldsettingsvn-ini
              mountPath: /tmp/PalWorldSettings.ini
              subPath: ./tmp/PalWorldSettings.ini
            - name: vn-palworld
              mountPath: /palworld
      volumes:
        - name: vn-tmpvn-palworldsettingsvn-ini
          configMap:
            name: ${{ defaults.app_name }}
            items:
              - key: vn-tmpvn-palworldsettingsvn-ini
                path: ./tmp/PalWorldSettings.ini
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /palworld
          value: '10'
        name: vn-palworld
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ defaults.app_name }}
data:
  vn-tmpvn-palworldsettingsvn-ini: |-
    [/Script/Pal.PalGameWorldSettings]
    OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=72.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,ServerName="Default Palworld Server",ServerDescription="",AdminPassword="",ServerPassword="",PublicPort=8211,PublicIP="",RCONEnabled=true,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  type: NodePort
  ports:
    - protocol: UDP
      port: 8211
      targetPort: 8211
      name: game
    - protocol: UDP
      port: 27015
      targetPort: 27015
      name: query
  selector:
    app: ${{ defaults.app_name }}